sudo: required

language: python

services:
      - docker

before_install:
      - curl -L https://github.com/docker/compose/releases/download/1.6.1/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin

script:
      - LOCAL_TAG=`cat tag.txt`
      - if [ "$LOCAL_TAG" == ""  ]; then LOCAL_TAG=postgres; fi
      - echo $LOCAL_TAG
      - ./init $LOCAL_TAG
      - docker-compose up -d
      - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      #- CURRENT_BRANCH=$TRAVIS_BRANCH
      #- export MYTARDIS_CONFIG_TAG=`if [  "$MYTARDIS_CONFIG_TAG" == ""  ]; then echo "$LOCAL_TAG"; else echo "$MYTARDIS_CONFIG_TAG"; fi`

      - VERSION=`cat version.txt`
      - if [ "$VERSION" == ""  ]; then VERSION=latest; fi

      - REPO=$DOCKER_USERNAME/dockerchiminey_nginx:"$VERSION"-travis
      - docker commit -a "$DOCKER_AUTHOR" -m "auto build" `docker ps | grep --line-buffered  dockerchiminey_nginx  | awk '{print $1}'` $REPO
      - docker push $REPO

      - REPO=$DOCKER_USERNAME/dockerchiminey_monitor:"$VERSION"-travis
      - docker commit -a "$DOCKER_AUTHOR" -m "auto build" `docker ps | grep --line-buffered  dockerchiminey_monitor   | awk '{print $1}'` $REPO
      - docker push $REPO

      - REPO=$DOCKER_USERNAME/dockerchiminey_beat:"$VERSION"-travis
      - docker commit -a "$DOCKER_AUTHOR" -m "auto build" `docker ps | grep --line-buffered  dockerchiminey_beat  | awk '{print $1}'` $REPO
      - docker push $REPO

      - REPO=$DOCKER_USERNAME/dockerchiminey_chiminey:"$VERSION"-travis
      - docker commit -a "$DOCKER_AUTHOR" -m "auto build" `docker ps | grep --line-buffered  dockerchiminey_chiminey   | awk '{print $1}'` $REPO
      - docker push $REPO

      - REPO=$DOCKER_USERNAME/dockerchiminey_celery:"$VERSION"-travis
      - docker commit -a "$DOCKER_AUTHOR" -m "auto build" `docker ps | grep --line-buffered  dockerchiminey_celery   | awk '{print $1}'` $REPO
      - docker push $REPO
