version: "2"

services:

    chiminey:
        extends:
            file: docker-compose.yml
            service: chiminey
        build: chiminey-portal

    celerydefault:
        extends:
            file: docker-compose.yml
            service: celerydefault
        build: chiminey-portal

    celeryhightasks:
        extends:
            file: docker-compose.yml
            service: celeryhightasks
        build: chiminey-portal

    beat:
        extends:
            file: docker-compose.yml
            service: beat
        build: chiminey-portal


    nginx:
        extends:
            file: docker-compose.yml
            service: nginx
        build: chiminey-nginx

    db:
        extends:
            file: docker-compose.yml
            service: db
            
    redis:
        extends:
            file: docker-compose.yml
            service: redis


    monitor:
        extends:
            file: docker-compose.yml
            service: monitor

    makecerts:
        extends:
            file: docker-compose.yml
            service: makecerts

    ssh:
        extends:
            file: docker-=compose.yml
            service: ssh
# volumes:
#     srcstore:
#         driver: local
#
#     logstore:
#         driver: local
#
#     varstore:
#         driver: local
#
#     dbstore:
#         driver: local
#
#     chimineystore:
#         driver: local
#
#     redisstore:
#         driver: local
#
#     elasticstore:
#         driver: local
#
# networks:
#     chiminey:
#         driver: bridge
