chiminey:
  restart: always
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore

celery:
  restart: always
  build: chiminey-celery
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore

beat:
  restart: always
  build: chiminey-beat
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore

nginx:
  restart: always
  build: chiminey-nginx
  ports:
   - "80:80"
  volumes_from:
   - chiminey
  links:
   - chiminey:chiminey

db:
  restart: always
  image: postgres
  volumes_from:
    - dbstore
  environment:
    - POSTGRES_PASSWORD=mysecretpassword

# rabbitmq:
#   restart: always
#   image: tutum/rabbitmq
#   volumes_from:
#    - rabbitmqstore
#   expose:
#    - "5672"
#    - "15672"
#   hostname: "amqp.local"
#   environment:
#    - RABBITMQ_PASS=pass

redis:
  restart: always
  image: redis
  volumes_from:
    - redisstore
  expose:
    - "6379"

# rabbitmqamb:
#   restart: always
#   image: cpuguy83/docker-grand-ambassador
#   volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#   environment:
#    - RABBITMQ_PASS=pass
#   command: "-name dockerchiminey_rabbitmq_1"

monitor:
  restart: always
  build: chiminey-monitor
  #image: iserko/docker-celery-flower
  ports:
    - "5555:5555"
  links:
    - redis:redis
    #- rabbitmqamb:rabbitmq
  environment:
    - CELERY_BROKER_URL=redis://redis:6379//
  command:
    - "--broker_api=http://redis:6379/api/"
    #- "--broker_api=http://admin:pass@redis:6379/api/"
    #- "--basic_auth=chiminey:pass"

chimineystore:
  build: chiminey-portal
  volumes:
   #- $PWD/current:/opt/chiminey/current
   - /store
  command: true

dbstore:
  image: postgres
  volumes:
   - /var/lib/postgresql
  command: true

# rabbitmqstore:
#   image: tutum/rabbitmq
#   volumes:
#     - /data/mnesia
#   command: true

redisstore:
  image: redis
  volumes:
    - /data
  command: true

# syslog:
#   restart: always
#   build: chiminey--syslog
#   volumes:
#   # see https://jpetazzo  .github.io/2014/08/24/syslog-docker/
#     - /tmp/syslogdev:/dev
# #  volumes_from:
# #    - logstore




