chiminey:
  restart: always
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore

celery:
  restart: always
  build: chiminey-celery
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore

beat:
  restart: always
  build: chiminey-beat
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore

nginx:
  restart: always
  build: chiminey-nginx
  ports:
   - "80:80"
  volumes_from:
   - chiminey
  links:
   - chiminey:chiminey
   - monitor:monitor

db:
  restart: always
  image: postgres
  volumes_from:
    - dbstore
  environment:
    - POSTGRES_PASSWORD=mysecretpassword

redis:
  restart: always
  image: redis
  volumes_from:
    - redisstore
  expose:
    - "6379"

monitor:
  restart: always
  build: chiminey-monitor
  ports:
    #- "5555:5555"
    - "5555:5555"
  links:
    - redis:redis
  environment:
    - CELERY_BROKER_URL=redis://redis:6379//
  command:
    - "--broker_api=redis://redis:6379//"
    - "--basic_auth=chiminey:pass"

chimineystore:
  build: chiminey-portal
  volumes:
   #- $PWD/current:/opt/chiminey/current
   - /var/chiminey/remotesys
  command: true

dbstore:
  image: postgres
  volumes:
   - /var/lib/postgresql
  command: true

redisstore:
  image: redis
  volumes:
    - /data
  command: true
