chiminey:
  restart: on-failure:5
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
   - nginxamb:nginxamb
  volumes_from:
   - chimineystore
   - logsstore
  command:
   - "gunicorn"
  volumes:
   - /etc/localtime:/etc/localtime:ro
  environment:
   - APIHOST=http://nginxamb/
   - GUNICORN_LOG_LEVEL=DEBUG
   - CHIMINEY_LOG_FILE=chiminey.log
   - CELERY_POLL_TIME=10
   - DJANGO_DEBUG=0
   - LOGGER_LEVEL=DEBUG

celery:
  restart: on-failure:5
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore
   - logsstore
  command:
    - "celery"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/chiminey
  environment:
    - CELERY_LOG_LEVEL=DEBUG
    - CHIMINEY_LOG_FILE=celery/celery.log
    - CELERY_POLL_TIME=10
    - DJANGO_DEBUG=0
    - LOGGER_LEVEL=DEBUG

beat:
  restart: on-failure:5
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore
   - logsstore
  command:
    - "beat"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/beat
  environment:
   - CHIMINEY_LOG_FILE=beat/beat.log
   - CELERY_POLL_TIME=10
   - DJANGO_DEBUG=0
   - LOGGER_LEVEL=DEBUG

nginx:
  restart: on-failure:5
  build: chiminey-nginx
  volumes_from:
   - chiminey
   - logsstore
  volumes:
    #- ./certs:/opt/certs:ro
    - /etc/localtime:/etc/localtime:ro
  expose:
    - 5601
    - 8080
    - 80
    - 443
    - 5555
  links:
   - chiminey:chiminey
   - kibana:kibana
   - cadvisor:cadvisor
   - monitor:monitor

nginxamb:
  restart: on-failure:5
  image: cpuguy83/docker-grand-ambassador
  ports:
   - 80:80
   - 443:443
   - 5601:5601
   - 8080:8080
   - 5555:5555
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  environment:
   - RABBITMQ_PASS=pass
  command: "-name dockerchiminey_nginx_1"

db:
  restart: on-failure:5
  image: postgres:9.4.5
  volumes_from:
    - dbstore
  environment:
    - POSTGRES_PASSWORD=mysecretpassword

redis:
  restart: on-failure:5
  image: redis:3.0.5
  volumes_from:
    - redisstore
  expose:
    - 6379

monitor:
  restart: on-failure:5
  build: chiminey-monitor
  expose:
    - 5555
  links:
    - redis:redis
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - CELERY_BROKER_URL=redis://redis:6379//
  command:
    - "--broker_api=redis://redis:6379//"
 #   - "--broker=redis://redis:6379//"
    - "--basic_auth=chiminey:pass"
#    - "--persistent=True"

chimineystore:
  build: chiminey-portal
  volumes:
   - /var/chiminey/remotesys
  command:
    - "store"

dbstore:
  image: postgres:9.4.5
  volumes:
   - /var/lib/postgresql
  command:
   - "true"

redisstore:
  image: redis:3.0.5
  volumes:
    - /data
  command:
    - "true"

logsstore:
  build: chiminey-portal
  volumes:
    - /logs
  command: "true"

elasticsearch:
 restart: on-failure:5
 image: denibertovic/elasticsearch
 volumes:
     - ./logs/elasticsearch:/opt/elasticsearch/logs
     - ./config-examples/elasticsearch:/opt/elasticsearch/config
     - ./data/elasticsearch:/opt/elasticsearch/data

logstash:
  restart: on-failure:5
  image: denibertovic/logstash
  links:
      - elasticsearch
  volumes:
      - ./config-examples/logstash:/opt/conf
      - ./certs:/opt/certs
      - ./logs/logstash:/opt/logs
  volumes_from:
      - logsstore

kibana:
  restart: on-failure:5
  image: denibertovic/kibana
  links:
      - elasticsearch
  volumes:
      - ./logs/kibana:/logs
      - ./config-examples/kibana:/kibana/config
  expose:
      - 5601

cadvisor:
   restart: on-failure:5
   image: google/cadvisor:latest
   privileged: true
   volumes:
     - /:/rootfs:ro
     - /var/run:/var/run:rw
     - /sys:/sys:ro
     - /var/lib/docker/:/var/lib/docker:ro
     - /cgroup:/cgroup:ro
   #command:
     #- '-storage_driver="elasticsearch"' 
     #- "-alsologtostderr=true"
     #- '-storage_driver_es_host="https://elasticsearch:9200"'
   expose:
     - 8080
