chiminey:
  restart: always
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore
   - logsstore
  command:
   - "gunicorn"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   #- ./src:/opt/chiminey
  environment:
   - APIHOST=http://118.138.241.38/
   - GUNICORN_LOG_LEVEL=WARN
   - CHIMINEY_LOG_FILE=chiminey.log
   - CELERY_POLL_TIME=10
   - DJANGO_DEBUG=0

celery:
  restart: always
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore
   - logsstore
  command:
    - "celery"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/chiminey
    #- ./src:/opt/chiminey
  environment:
    - CELERY_LOG_LEVEL=DEBUG
    - CHIMINEY_LOG_FILE=celery/celery.log
    - CELERY_POLL_TIME=10
    - DJANGO_DEBUG=0

beat:
  restart: always
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore
   - logsstore
  command:
    - "beat"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/beat
    #- ./src:/opt/chiminey
  environment:
   - CHIMINEY_LOG_FILE=beat/beat.log
   - CELERY_POLL_TIME=10
   - DJANGO_DEBUG=0

nginx:
  restart: always
  build: chiminey-nginx
  ports:
   - "80:80"
   - "433:433"
  volumes_from:
   - chiminey
   - logsstore
  volumes:
    - ./certs:/opt/certs:ro
    - /etc/localtime:/etc/localtime:ro
  links:
   - chiminey:chiminey
#    - monitor:monitor

db:
  restart: always
  image: postgres
  volumes_from:
    - dbstore
  environment:
    - POSTGRES_PASSWORD=mysecretpassword

redis:
  restart: always
  image: redis
  volumes_from:
    - redisstore
  expose:
    - "6379"

monitor:
  restart: always
  build: chiminey-monitor
  ports:
    - "8080:5555"
  links:
    - redis:redis
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - CELERY_BROKER_URL=redis://redis:6379//
  command:
    - "--broker_api=redis://redis:6379//"
 #   - "--broker=redis://redis:6379//"
    - "--basic_auth=chiminey:pass"
#    - "--persistent=True"

chimineystore:
  build: chiminey-portal
  volumes:
   - /var/chiminey/remotesys
  command:
    - "store"

dbstore:
  image: postgres
  volumes:
   - /var/lib/postgresql
  command:
   - "true"

redisstore:
  image: redis
  volumes:
    - /data
  command:
    - "true"

logsstore:
  build: chiminey-portal
  volumes:
    - /logs
  command: "true"

elasticsearch:
 image: denibertovic/elasticsearch
 volumes:
     - ./logs/elasticsearch:/opt/elasticsearch/logs
     - ./config-examples/elasticsearch:/opt/elasticsearch/config
     - ./data/elasticsearch:/opt/elasticsearch/data
 #ports:
     #- "9200:9200"
     #- "9300:9300"
 restart: always

logstash:
  image: denibertovic/logstash
  links:
      - elasticsearch
  volumes:
      - ./config-examples/logstash:/opt/conf
      - ./certs:/opt/certs
      - ./logs/logstash:/opt/logs
  volumes_from:
      - logsstore
  #ports:
      #- "514:514"
      #- "5043:5043"
      #- "9292:9292"
  restart: always

# kibana:
#   image: denibertovic/kibana
#   links:
#       - elasticsearch
#   volumes:
#       - ./logs/kibana:/logs
#       - ./config-examples/kibana:/kibana/config
#   ports:
#       - "5601:5601"
#   restart: always

# cadvisor:
#   image: google/cadvisor:latest
#   volumes:
#     - /:/rootfs:ro
#     - /var/run:/var/run:rw
#     - /sys:/sys:ro
#     - /var/lib/docker/:/var/lib/docker:ro
#   ports:
#     - "8080:8080"
#   restart: always


