chiminey:
  restart: always
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore
   - logsstore
  command:
   - "gunicorn"

celery:
  restart: always
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore
   - logsstore
  command:
    - "celery"

beat:
  restart: always
  build: chiminey-portal
  links:
   - db:db
   - redis:redis
  volumes_from:
   - chimineystore
   - logsstore
  command:
    - "beat"
  environment:
   - LOG_FILE=beat

nginx:
  restart: always
  build: chiminey-nginx
  ports:
   - "80:80"
  volumes_from:
   - chiminey
   - logsstore
  links:
   - chiminey:chiminey
   - monitor:monitor

db:
  restart: always
  image: postgres
  volumes_from:
    - dbstore
  environment:
    - POSTGRES_PASSWORD=mysecretpassword

redis:
  restart: always
  image: redis
  volumes_from:
    - redisstore
  expose:
    - "6379"

monitor:
  restart: always
  build: chiminey-monitor
  ports:
    - "5555:5555"
  links:
    - redis:redis
  environment:
    - CELERY_BROKER_URL=redis://redis:6379//
  command:
    - "--broker_api=redis://redis:6379//"
    - "--basic_auth=chiminey:pass"

chimineystore:
  build: chiminey-portal
  volumes:
   - /var/chiminey/remotesys
  command: 
    - "store"

dbstore:
  image: postgres
  volumes:
   - /var/lib/postgresql
  command: true

redisstore:
  image: redis
  volumes:
    - /data
  command: true

logsstore:
  build: chiminey-portal
  volumes:
    - /logs
  command: true

