version: "2"

services:

    selenium:
        image: selenium/standalone-chrome
        environment:
            JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
        networks:
            - chiminey
networks:
    chiminey:
        external:
            name: dockerchiminey_chiminey
